spring:
  application:
    name: "Work From Here"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/workfromhere_db
    username: wfhadmin
    password: wfhpassword
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

